/**
 * Audio property extraction, asserted against fixtures generated with KNOWN
 * properties (see tests/fixtures/README.md for how they were made).
 *
 * The point of generating fixtures rather than committing a random mp3 is that
 * we know the right answer independently, so a wrong number is detectable.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';

import { analyzeAudio } from '../app/audio.js';

const fx = (n) => `tests/fixtures/${n}`;
const has = (n) => existsSync(fx(n));

// Fixtures are generated by tests/fixtures/generate.js and are committed.
const REQUIRED = ['tone_44k.wav', 'tone_22k_128k.mp3', 'browser_like.webm',
  'clipped.wav', 'speech_quiet_room.wav', 'speech_loud_room.wav'];

test('fixtures are present', () => {
  for (const f of REQUIRED) assert.ok(has(f), `missing fixture ${f} - run: node tests/fixtures/generate.js`);
});

test('sample rate is read exactly, not guessed', async () => {
  assert.equal((await analyzeAudio(fx('tone_44k.wav'))).sample_rate_hz, 44100);
  assert.equal((await analyzeAudio(fx('tone_22k_128k.mp3'))).sample_rate_hz, 22050);
  assert.equal((await analyzeAudio(fx('browser_like.webm'))).sample_rate_hz, 48000);
});

test('duration is read to sub-second accuracy', async () => {
  const r = await analyzeAudio(fx('tone_44k.wav'));
  assert.ok(Math.abs(r.duration_sec - 3) < 0.05, `expected ~3s, got ${r.duration_sec}`);
});

test('channels and codec come through', async () => {
  const stereo = await analyzeAudio(fx('tone_44k.wav'));
  assert.equal(stereo.channels, 2);
  assert.equal(stereo.codec, 'pcm_s16le');

  const webm = await analyzeAudio(fx('browser_like.webm'));
  assert.equal(webm.channels, 1);
  assert.equal(webm.codec, 'opus');
});

test('bitrate: an uncompressed WAV matches the arithmetic exactly', async () => {
  // 44100 Hz x 16 bit x 2 channels = 1,411,200 bps
  const r = await analyzeAudio(fx('tone_44k.wav'));
  assert.equal(r.bitrate_kbps, 1411.2);
  assert.equal(r.bitrate_source, 'declared');
});

test('bitrate: a 128k MP3 reports 128k', async () => {
  const r = await analyzeAudio(fx('tone_22k_128k.mp3'));
  assert.equal(r.bitrate_kbps, 128);
});

test('bitrate is always produced, even for browser WebM', async () => {
  // This is the case that breaks naive implementations: WebM/Opus frequently
  // declares no bitrate, so it must be derived from size and duration.
  const r = await analyzeAudio(fx('browser_like.webm'));
  assert.ok(r.bitrate_kbps > 0, 'no bitrate for the browser-style file');
  assert.ok(['declared', 'derived from size/duration'].includes(r.bitrate_source));
});

test('loudness agrees with ffmpeg volumedetect (independent tool)', async () => {
  // volumedetect reports mean -30.1 dB / max -27.1 dB for this file.
  const r = await analyzeAudio(fx('tone_44k.wav'));
  assert.ok(Math.abs(r.loudness_dbfs - (-30.1)) < 0.3, `RMS ${r.loudness_dbfs} != -30.1`);
  assert.ok(Math.abs(r.peak_dbfs - (-27.1)) < 0.3, `peak ${r.peak_dbfs} != -27.1`);
});

test('for a pure sine, peak sits 3.01 dB above RMS', async () => {
  // A sine's RMS is peak/sqrt(2). If this drifts, the dBFS maths is wrong.
  const r = await analyzeAudio(fx('tone_44k.wav'));
  assert.ok(Math.abs((r.peak_dbfs - r.loudness_dbfs) - 3.01) < 0.1);
});

test('LUFS is produced and is in a sane range', async () => {
  const r = await analyzeAudio(fx('tone_44k.wav'));
  assert.ok(r.loudness_lufs !== null, 'no LUFS value');
  assert.ok(r.loudness_lufs < 0 && r.loudness_lufs > -70, `implausible LUFS ${r.loudness_lufs}`);
});

test('clipping is detected and quantified', async () => {
  const clipped = await analyzeAudio(fx('clipped.wav'));
  assert.ok(clipped.clipping_pct > 5, `expected heavy clipping, got ${clipped.clipping_pct}%`);
  assert.match(clipped.quality_label, /clipped/);

  const clean = await analyzeAudio(fx('tone_44k.wav'));
  assert.equal(clean.clipping_pct, 0);
});

test('SNR separates a quiet room from a loud one', async () => {
  const quiet = await analyzeAudio(fx('speech_quiet_room.wav'));
  const loud = await analyzeAudio(fx('speech_loud_room.wav'));

  assert.ok(quiet.snr_db > 25, `quiet room SNR too low: ${quiet.snr_db}`);
  assert.ok(loud.snr_db < 10, `loud room SNR too high: ${loud.snr_db}`);
  assert.ok(quiet.noise_floor_dbfs < loud.noise_floor_dbfs, 'noise floors are the wrong way round');

  assert.equal(quiet.quality_label, 'good');
  assert.match(loud.quality_label, /noisy/);
});

test('continuous audio is reported as unmeasurable, not as noisy', async () => {
  // A held tone has no pauses, so there is no background to measure against.
  // Claiming "noisy" there would be a false positive - the honest answer is
  // that the estimate does not apply.
  const r = await analyzeAudio(fx('tone_44k.wav'));
  assert.match(r.quality_label, /^unknown/);
  assert.match(r.quality_label, /no pauses/);
});

test('a non-audio file fails softly instead of throwing', async () => {
  const r = await analyzeAudio('package.json');
  assert.ok(r.analysis_error, 'expected an analysis_error');
  assert.equal(r.duration_sec, null);
});

test('a missing file fails softly too', async () => {
  const r = await analyzeAudio('tests/fixtures/does-not-exist.wav');
  assert.ok(r.analysis_error);
});
